version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - Internal
  - dependencies
  ignore:
  - dependency-name: lerna
    versions:
    - "< 4, >= 3.a"
  - dependency-name: parcel-bundler
    versions:
    - 1.12.4
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.32
    - 1.2.34
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.44.0
