language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"
  - "8"
  - "10"
script: yarn run lerna build
notifications:
    email: false
