language: node_js

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - command -v npx >/dev/null 2>&1 || npm i --silent -g npx

install: npm install --silent

before_script: npx lerna bootstrap
script: npx lerna run build

notifications:
    email: false
