language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install: yarn --ignore-engines
script: yarn lerna build
notifications:
    email: false
