language: node_js

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

node_js:
  - "6"
  - "8"

before_install:
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

install: npm ci

script: npx lerna bootstrap && npx lerna run build

notifications:
    email: false
