language: node_js

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

node_js:
  - "8"
  - "10"

install: npm install --silent

script: npm run build

notifications:
    email: false
