install:
  - npm install --silent --global npx
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install >nul
platform:
  - x86
  - x64
before_build:
  - npx lerna bootstrap
build_script:
  - npx lerna run build
cache:
  - '%AppData%/npm-cache'
  - '%AppData%/npm'
