backend:
  name: test-repo
  login: false
media_folder: assets
collections:
- name: example
  label: Example
  editor:
    preview: false
  files:
  - file: _data/color.yml
    name: color-widget
    label: Color Widget
    fields:
    - name: color
      label: Color
      widget: color

  - file: _data/fontawesome.yml
    name: fontawesome-widget
    label: Fontawesome
    fields:
    - name: fontawesome-solid
      label: Fontawesome Solid Widget
      widget: fontawesome-solid
    - name: fontawesome-brands
      label: Fontawesome Brands Widget
      widget: fontawesome-brands
    - name: fontawesome-regular
      label: Fontawesome Regular Widget
      widget: fontawesome-regular

  - file: _data/material-icons.yml
    name: material-icons-widget
    label: Material Icons Widget
    fields:
    - name: material-icons
      label: Material Icons
      widget: material-icons

  - file: _data/native-color.yml
    name: native-color-widget
    label: Native Color Widget
    fields:
    - name: native-color
      label: Native Color
      widget: native-color
