backend:
  name: test-repo
  login: false

media_folder: assets
collections:
  - name: "example"
    label: "Example Widgets"
    delete: false
    editor:
      preview: false
    files:
      - name: "color"
        label: "Color Widget"
        file: "_data/example.yml"
        description: "Color Widget Example"
        fields:
          - {label: "Color Widget", name: "color", widget: "color"}
