backend:
  name: test-repo
  login: false

media_folder: assets
collections:
  - name: "example"
    label: "Example Widgets"
    delete: false
    editor:
      preview: false
    files:
      - name: "color"
        label: "Example Widgets"
        file: "_data/example.yml"
        fields:
          - {label: "Color Widget", name: "color", widget: "color"}
          - {label: "Native Color Widget", name: "native-color", widget: "native-color"}
          - {label: "Material Icons Widget", name: "material-icons", widget: "material-icons"}
