backend:
  name: test-repo
  login: false
media_folder: assets
collections:
- name: example
  label: Example
  files:
  - name: material-icons
    label: Material Icons
    file: _data/material-icons.json
    fields:
      - name: icon
        label: Icon
        widget: material-icons
      - name: iconlist
        label: Icon List
        widget: list
        fields:
          - {name: icon, label: Icon, widget: material-icons}
